### ISSUE TITLE
出视频教程

### ISSUE THREAD

**Issue by share001001** [idea4good/GuiLite#12]
directUI 就是所有界面组件全部用画笔画出来，看了你的代码也是这样， core和gui 讲 display surface framebuffer上下文层次关系和绘图原理，讲事件循环机制怎么传递。讲具体一个示例项目应用从创建到使用的流程。。。已经花了一个星期看你的gui和core部分，代码简洁，风格优雅，非常棒的，就是一点注释都没有 好尴尬。。。很多很好的东西因为没有推广好而夭折，要知道有很多大神根本不屑于推广。。。希望这个开源项目能得到推广流传下去，我主攻嵌入式arm-linux方面的项目，底层无界面代码写的再好，可是没有ui给展示出来。。。qt太庞大，minigui技术支持不好。。。我曾经也想过用直接操作linux下的framebuffer来绘制ui，可是ui不是一两天就能搞好的，终于在逛今日头条的时候推送了guilite仅用5000行代码实现跨平台ui框架，甚是欢喜。。。已经沉溺于大神的代码中。。。

**Comment by idea4good** [comment]
谢谢您的支持！有些问题，可能需要随后的视频来回答。“事件循环”问题，相对简单，希望下面的回答，可以有所帮助：

当前的事件仅有两种，一种是“用户定义事件”，另一种是“人机交互事件”。仅“人机交互事件”跟UI相关，它的性质如下：

1. 事件内容：仅包含鼠标（手指）的按下/弹起及其位置信息（定义见：core::msg.h::MSG_INFO）
2. 事件通过管道传输：core::msg_linux.cpp::s_hid_fifo
3. 事件发送：由上层应用发起，以linux为例，代码见：buildlinux::std_io.cpp::press_down/press_release
4. 事件接收：由c_gesture::task来最终获取，c_gesture跟display一一对应，往往同时创建，代码见:samplecode/source/ui_tree/root.cpp::load_ui_single
5. 事件解析：由c_gesture::handle_hid_msg转交给UI的根节点m_root完成。解析工作有：1. 解析处位置信息；2. 根据位置信息逐层查找子窗口，确定子窗口位置（代码见: core::wnd.cpp::on_touch_down），然后，调用其相应的响应函数(例如：gui::button.cpp::on_touch_down)。

**Comment by idea4good** [comment]
msg.h/msg_xxx.cpp的代码确实存在一些不合理的地方。我们会对其进行重构，代码约会减少近百行，请注意更新消息

**Comment by idea4good** [comment]
用3D程序作了[一个教](https://v.youku.com/v_show/id_XNDI4ODE1ODcwOA)程：用于解释：滑动及多图层叠加原理，希望对你有帮助。

后续还会不断推出3D的视频教程，敬请关注。
