### ISSUE TITLE
实践反馈

### ISSUE THREAD

**Issue by RgznLbq** [idea4good/GuiLite#15]
CPU使用过高，如果绘制股票行情图、雷达仪表等问题会很突出。中文字符乱码问题。缺少注意事项：比如必须添加一个字体否咋会崩溃。改变Helloxxx等实例窗口大小时会露出MFC的窗口。

**Comment by idea4good** [comment]
cpu使用率过高问题，已经解决，请更新代码，再验证一下

**Comment by RgznLbq** [comment]
> cpu使用率过高问题，已经解决，请更新代码，再验证一下

![image](https://user-images.githubusercontent.com/30398914/50466455-a2c64700-09d8-11e9-9ea5-5aa267d2b19b.png)
还是挺高的。

**Comment by idea4good** [comment]
当界面在进行大面积刷新的时候，会占用较大的CPU资源，这是合理的，可能无法避免
在界面处于静止状态，或小面积刷新时，CPU使用率就会降下来；你可以再看下小面积刷新（或静止）情况下的CPU使用率

**Comment by idea4good** [comment]
当界面在进行大面积刷新的时候，会占用较大的CPU资源，这是合理的，可能无法避免
在界面处于静止状态，或小面积刷新时，CPU使用率就会降下来；你可以再看下小面积刷新（或静止）情况下的CPU使用率。比如：选择helloxxx的实例看一下

**Comment by idea4good** [comment]
关于添加字体，导致程序崩溃的问题，是assert所致，我们换成了更加友好的方式来提醒开发者：
1. 如果没有该字体资源，输出的文字会出现**红色的“X”**
2. 如果有字体资源，但没有制作某个字的点阵，该字会出现**白色的“X”**
