### ISSUE TITLE
mingw  gcc 8.1 building error 

### ISSUE THREAD

**Issue by khan-lau** [idea4good/GuiLite#17]
[ 28%] Building CXX object core/CMakeFiles/core.dir/src/wave_ctrl.cpp.obj
D:\Users\Administrator\Downloads\GuiLite-master\core\src\wave_ctrl.cpp: In member function 'void c_wave_ctrl::refresh_wa
ve(unsigned char)':
D:\Users\Administrator\Downloads\GuiLite-master\core\src\wave_ctrl.cpp:136:49: error: cast from 'c_wave_ctrl*' to 'long
unsigned int' loses precision [-fpermissive]
        (frame | (speed << 8) | (((unsigned long)this & 0xffff) << 16)));
                                                 ^~~~
make[2]: *** [core\CMakeFiles\core.dir\build.make:147: core/CMakeFiles/core.dir/src/wave_ctrl.cpp.obj] Error 1
make[1]: *** [CMakeFiles\Makefile2:90: core/CMakeFiles/core.dir/all] Error 2

**Comment by idea4good** [comment]
嗯，需要加上一个编译选项-fpermissive

如果想尽快编译通过，请选择其他编译器，比如纯linux环境下的编译器
