### ISSUE TITLE
reserved identifier violation

### ISSUE THREAD

**Issue by elfring** [idea4good/GuiLite#22]
I would like to point out that identifiers like “[`_API_H_`](https://github.com/idea4good/GuiLite/blob/bf2df8527fae95d70dce567b594524b1115d794f/core/core_include/api.h#L1 "Update candidate")” and “[`_DISPLAY_H_`](https://github.com/idea4good/GuiLite/blob/32b4b3c95ccae7d1df4d84f22d500d2aa8373a5e/core/core_include/display.h#L1 "Another update candidate")” [do not fit](https://www.securecoding.cert.org/confluence/display/cplusplus/DCL51-CPP.+Do+not+declare+or+define+a+reserved+identifier#DCL51-CPP.Donotdeclareordefineareservedidentifier-NoncompliantCodeExample%28HeaderGuard%29 "Do not declare an identifier which is reserved for the compiler implementation.") to the expected naming convention of the C++ language standard.
Would you like to adjust your selection for unique names?

**Comment by elfring** [comment]
I would prefer to [keep this issue open](https://stackoverflow.com/questions/228783/what-are-the-rules-about-using-an-underscore-in-a-c-identifier#answer-228797 "What are the rules about using an underscore in a C++ identifier?") until it will be fixed finally.

**Comment by idea4good** [comment]
Sure, It looks the issue has been fixed, would you please take a check?

Thanks


Sent from Mail<https://go.microsoft.com/fwlink/?LinkId=550986> for Windows 10

________________________________

**Comment by elfring** [comment]
[An update candidate was left over](https://github.com/idea4good/GuiLite/blob/356fbd146b0b2964116fad3a085d8b7a9b03cd85/core/core_include/api.h#L28).
