### ISSUE TITLE
Make include guards unique

### ISSUE THREAD

**Issue by elfring** [idea4good/GuiLite#27]
I find that include guards like “[`API_H`](https://github.com/idea4good/GuiLite/blob/356fbd146b0b2964116fad3a085d8b7a9b03cd85/core/core_include/api.h#L1)” and “[`MSG_H`](https://github.com/idea4good/GuiLite/blob/356fbd146b0b2964116fad3a085d8b7a9b03cd85/core/core_include/msg.h#L1)” are too short for the safe reuse of your header files (when they belong to an application programming interface).

**Comment by idea4good** [comment]
Agree, Would you please make a PR for the issue?

**Comment by elfring** [comment]
Which [longer name pattern would you find acceptable for the include guards](https://en.wikipedia.org/wiki/Include_guard#Difficulties "Coherent naming scheme for include guards?") of this software?
