### ISSUE TITLE
Example for UWP?

### ISSUE THREAD

**Issue by meteorsnows** [idea4good/GuiLite#31]
Windows.UI.ViewManagement have official support of Compact Overlay (PIP) that won't disappear if you Win+D (Show Desktop)..

Would like to learn how to integrate it with Visual Studio UWP project. Normal/ Classic desktop app can't call the API to switch to PIP mode.

Windows.UI.ViewManagement compact Overlay 只能從 UWP project使用， Desktop App, Desktop Bridge, 和 Microsoft centennial (同名應該)，都無法使用。

C++ 我沒啥經驗，求指導，和demo.

**Comment by idea4good** [comment]
You can check this [demo](https://github.com/idea4good/GuiLiteSamples/tree/master/HostMonitor/BuildUWP)

**Comment by meteorsnows** [comment]
Thanks. Awesome

At least there are more viable cross platform UI on UWP.
All the popular UI framework on .NET like Xamarin, AvaloniaUI, etc, haven't get basic getting started example for UWP app.
