### ISSUE TITLE
Use std::max and std::min instead of custom macros

### ISSUE THREAD

**Issue by Raincode** [idea4good/GuiLite#39]
Hello,

since this library uses C++, is there a specific reason not to use `std::max` and `std::min`, which IMHO are superior to defining custom macros:
```
#define MAX(a,b) (((a)>(b))?(a):(b))
#define MIN(a,b) (((a)<(b))?(a):(b))
```

Just a small suggestion I stumbled upon spontaneously :)

**Comment by idea4good** [comment]
I love STD, but some MCU IDE do not support STD, or STD would make bin file much bigger.
