### ISSUE TITLE
Waveform sample in QT widget

### ISSUE THREAD

**Issue by ameenakshi06** [idea4good/GuiLite#42]
Hi,

I liked GuiLite project and the sample which you have showcased is awesome.
I'm a QT developer i have checked the samples and didn't found the waveform drawing in QT application.
Is waveform drawing is possible in QT widget?.
I have planned to use this toolkit for drawing audio waveform please suggest me, how we can use it in QT widget.

Thanks,
Sundaram

**Comment by idea4good** [comment]
It looks no waveform widget in QT, you maybe need develop waveform widget yourself.
