### ISSUE TITLE
please remove porn in readme.md

### ISSUE THREAD

**Issue by graysuit** [idea4good/GuiLite#50]
Respected developer @idea4good 

If you don't mind, please remove that pornish and disgusting image:
https://github.com/idea4good/GuiLiteSamples#hello-transparent

Thanks

**Comment by untyper** [comment]
Oh come on...

**Comment by idea4good** [comment]
@graysuit 
Do a little bit change, pls review it.

**Comment by graysuit** [comment]
@idea4good 
Thanks.
But its too little bit. Actually whole girl is porn.
Please replace this girl image with any other image.

**Comment by Pablo2048** [comment]
Oh, come on - it is definitely NOT a porn by definition ( https://en.wikipedia.org/wiki/Pornography ). At most it can be defined as nudity ( https://en.wikipedia.org/wiki/Nudity ) in some society...

**Comment by graysuit** [comment]
@Pablo2048 
We don't on wikipedia, We depend on our senses.
I don't care whether its pronounced as `porn` or `nudity`.
This image disturbs sexual habits and that's it.
Many website do show warning if it have some adult content so that childs can go back.

**Comment by Pablo2048** [comment]
Well, actually it disturb sexual habits only to you. That image was there for 12 months and nobody complain...

**Comment by idea4good** [comment]
> @idea4good
> Thanks.
> But its too little bit. Actually whole girl is porn.
> Please replace this girl image with any other image.

will change the whole image soon

**Comment by graysuit** [comment]
@Pablo2048 
By the way, are you teenager ?

**Comment by Pablo2048** [comment]
> @Pablo2048
> By the way, are you teenager ?

No, I'm very probably older than you.

**Comment by untyper** [comment]
@graysuit You are too sensitive. Toughen up. The world does not revolve around you or your opinions.
And that image is certainly not porn by any definition besides the one you just made up.

Otherwise I could just aswell claim that your profile picture "disturbs sexual habits", and it'd be just as valid as your opinion.

**Comment by idea4good** [comment]
Remove that for peace.
Have a good day, guys

**Comment by graysuit** [comment]
> 
> 
> Remove that for peace.
> Have a good day, guys

Impressive ! I am really thankful to you.

@Pablo2048 and @untyper 
Don't be aggressive. Opposite opinions doesn't mean that anyone is enemy.
And also we should NOT do personal attacks.
 
Nude photos are always prohibited in most offices, companies, websites. e.g google, blogger, youtube, facebook.
At-least they show warning before showing content to user.
They are big companies with over millions of developers. Why they do so ?
Its task for you find.

And if my any word or action disturbs you, then please accept my apologies.  
Ending this useless discussion. Thanks.
