### ISSUE TITLE
Need source for the xWindow to build for Linux on other processors

### ISSUE THREAD

**Issue by RolandHughes** [idea4good/GuiLite#63]
Every one of the samples comes with an xWindow ELF binary.

![image](https://user-images.githubusercontent.com/1883220/139596650-c1dd95ff-876e-4a13-ba7c-dd0fd1bd127a.png)

I don't see the source or build instructions for this file. We are running a recent version of Ubuntu on a non-x86 processor and would like to do some better GuiLite experiments. Writing directly to the physical /dev/fb0 technically "works" but is officially unsupported and not promised to remain working. We also don't get a mouse that way. X11 is installed, but there is no desktop running.

**Comment by idea4good** [comment]
https://github.com/idea4good/GuiLiteSamples/tree/master/ExternalWindow/X11
