### ISSUE TITLE
怎么用GO开发业务部分，有没有相关文档？

### ISSUE THREAD

**Issue by zhuwei** [idea4good/GuiLite#9]

**Comment by shmy** [comment]
同求

**Comment by idea4good** [comment]
思路应该是：C++作核心业务，然后使用某种桥接的方法跟golang发生联系，我们会尽快将这个想法以代码的形式体现出来

**Comment by sjqzhang** [comment]
非常好的想，要是能实现golang关注度马上又上另一个等级，加油💪

**Comment by idea4good** [comment]
已经支持Golang了，编译方法在[这里](https://github.com/idea4good/GuiLiteSamples/tree/master/HostMonitor)
